
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/mfadl237/Desktop/DevOps/Projects/Project-1/K8s/WordPress/data-wordpress