
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-app
      tier: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress-app
        tier: wordpress
    spec:
      containers:
      - image:  wordpress
        name:  wordpress-container
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name:  WORDPRESS_DB_HOST
          value:  mysql-svc   
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        ports:
        - containerPort:  80
          name:  wordpress-port
        volumeMounts:
        - mountPath: /var/www/html
          name: data-wordpress
      volumes:
        - name: data-wordpress
          persistentVolumeClaim:
            claimName: wordpress-pvc
