apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-sql
spec:
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name:  mysql-pod
      labels:
        app:  mysql-app
    spec:
      containers:
      - image:  mysql
        name:  my-sql-name-cont
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name:  MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name:  mysql-secret
        ports:
        - containerPort:  3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim: 
            claimName: mysql-pvc
      